Repository Shopify/ruby-lsp-rails, pull requests merged in 2024-09, with the labels that each got.

#445 Improve features documentation
  .github/workflows/publish_docs.yml
  .gitignore
  FEATURES.md
  README.md
  Rakefile
  misc/ruby-lsp-rails-controller-action-to-route.gif
  misc/ruby-lsp-rails-controller-action-to-view.gif
  misc/ruby-lsp-rails-debug.gif
  misc/ruby-lsp-rails-destroy-command.gif
  misc/ruby-lsp-rails-document-symbol-ar-model.gif
  misc/ruby-lsp-rails-file-operations-icon.gif
  misc/ruby-lsp-rails-generate-command.gif
  misc/ruby-lsp-rails-go-to-ar-associations.gif
  misc/ruby-lsp-rails-go-to-ar-dsl-definitions.gif
  misc/ruby-lsp-rails-go-to-route-definitions.gif
  misc/ruby-lsp-rails-run-in-terminal.gif
  misc/ruby-lsp-rails-run.gif
  misc/ruby-lsp-rails-test-document-symbol.gif
Labels: documentation

#447 Upgrade Sorbet
  Gemfile.lock
  lib/ruby_lsp/ruby_lsp_rails/support/location_builder.rb
Labels: chore

#448 Use regex to filter test runs for multiple classes in the same file
  lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
  test/ruby_lsp_rails/code_lens_test.rb
Labels: bugfix

#450 Prevent migration code lens from failing in unsaved files
  lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
Labels: bugfix

#453 Avoid need for special VOID return
  lib/ruby_lsp/ruby_lsp_rails/server.rb
  test/ruby_lsp_rails/server_test.rb
Labels: chore

#455 Point all documentation to the official Ruby LSP docs
  .github/workflows/ci.yml
  .github/workflows/publish_docs.yml
  FEATURES.md
  Gemfile
  Gemfile.lock
  README.md
  Rakefile
  misc/code_lens.gif
  misc/definition.gif
  misc/document_symbol.gif
  misc/hover.gif
  misc/ruby-lsp-rails-controller-action-to-route.gif
  misc/ruby-lsp-rails-controller-action-to-view.gif
  misc/ruby-lsp-rails-debug.gif
  misc/ruby-lsp-rails-destroy-command.gif
  misc/ruby-lsp-rails-document-symbol-ar-model.gif
  misc/ruby-lsp-rails-file-operations-icon.gif
  misc/ruby-lsp-rails-generate-command.gif
  misc/ruby-lsp-rails-go-to-ar-associations.gif
  misc/ruby-lsp-rails-go-to-ar-dsl-definitions.gif
  misc/ruby-lsp-rails-go-to-route-definitions.gif
  misc/ruby-lsp-rails-run-in-terminal.gif
  misc/ruby-lsp-rails-run.gif
  misc/ruby-lsp-rails-test-document-symbol.gif
Labels: documentation

#458 Add docs link to RubyGems metadata
  ruby-lsp-rails.gemspec
Labels: chore

#459 Upgrade Sorbet to v0.5.11577
  Gemfile.lock
Labels: chore

#462 Correct 'add-on' hyphenation
  README.md
  lib/ruby_lsp/ruby_lsp_rails/addon.rb
  lib/ruby_lsp/ruby_lsp_rails/server.rb
  test/ruby_lsp_rails/addon_test.rb
  test/ruby_lsp_rails/server_test.rb
Labels: chore

#466 Stop testing against Ruby 3.1 in CI
  .github/workflows/ci.yml
Labels: chore

#467 Use latest Ruby LSP release (v0.18.4)
  Gemfile.lock
  ruby-lsp-rails.gemspec
  sorbet/rbi/gems/ruby-lsp@0.18.4.rbi
Labels: chore
