Repository Shopify/ruby-lsp-rails, pull requests merged in 2024-11, with the labels that each got.

#503 Add support for checking for pending migrations and running them
  lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
  lib/ruby_lsp/ruby_lsp_rails/server.rb
  test/ruby_lsp_rails/server_test.rb
Labels: enhancement

#504 Check for pending migrations when watcher is fired
  lib/ruby_lsp/ruby_lsp_rails/addon.rb
  test/ruby_lsp_rails/addon_test.rb
  test/test_helper.rb
Labels: enhancement

#509 Remove usage of present? from hover
  lib/ruby_lsp/ruby_lsp_rails/hover.rb
Labels: bugfix

#517 Improve error handling for database problems
  lib/ruby_lsp/ruby_lsp_rails/server.rb
  test/ruby_lsp_rails/server_test.rb
Labels: bugfix

#520 Improve diagnostics for situations where Rails fails to boot
  lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
Labels: enhancement

#528 Remove redundant rescue in runner client
  lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
Labels: chore

#529 Update for changes to index enhancements API
  Gemfile.lock
  lib/ruby_lsp/ruby_lsp_rails/addon.rb
  lib/ruby_lsp/ruby_lsp_rails/indexing_enhancement.rb
  ruby-lsp-rails.gemspec
  sorbet/rbi/gems/ruby-lsp@0.22.0.rbi
  sorbet/rbi/gems/webrick@1.8.2.rbi
  sorbet/rbi/shims/ruby_lsp.rbi
  test/dummy/app/models/concerns/verifiable.rb
  test/dummy/app/models/user.rb
  test/ruby_lsp_rails/indexing_enhancement_test.rb
Labels: enhancement

#527 Unify all error handling for the server
  .vscode/settings.json
  lib/ruby_lsp/ruby_lsp_rails/server.rb
  test/ruby_lsp_rails/server_test.rb
Labels: bugfix

#535 Remove redundant Railtie
  lib/ruby-lsp-rails.rb
  lib/ruby_lsp_rails/railtie.rb
Labels: enhancement
