Repository Shopify/ruby-lsp-rails, pull requests merged in 2024-02, with the labels that each got.

#243 Avoid inspecting schema info for abstract classes
  lib/ruby_lsp_rails/rack_app.rb
  test/ruby_lsp_rails/rack_app_test.rb
Labels: bugfix

#248 Adjust server check stub
  test/ruby_lsp_rails/hover_test.rb
Labels: chore

#256 Switch to `rails runner` approach instead of Rack app
  README.md
  lib/ruby-lsp-rails.rb
  lib/ruby_lsp/ruby_lsp_rails/addon.rb
  lib/ruby_lsp/ruby_lsp_rails/hover.rb
  lib/ruby_lsp/ruby_lsp_rails/rails_client.rb
  lib/ruby_lsp_rails/rack_app.rb
  lib/ruby_lsp_rails/railtie.rb
  test/ruby_lsp_rails/addon_test.rb
  test/ruby_lsp_rails/hover_test.rb
  test/ruby_lsp_rails/rack_app_test.rb
  test/ruby_lsp_rails/rails_client_test.rb
  test/test_helper.rb
Labels: breaking-change

#266 Fallback to `NullClient` if initializing server fails
  lib/ruby_lsp/ruby_lsp_rails/addon.rb
  lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
  lib/ruby_lsp/ruby_lsp_rails/server.rb
  test/ruby_lsp_rails/hover_test.rb
  test/ruby_lsp_rails/runner_client_test.rb
  test/ruby_lsp_rails/server_test.rb
Labels: bugfix

#231 Support document symbol on ActiveSupport tests
  lib/ruby_lsp/ruby_lsp_rails/addon.rb
  lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
  lib/ruby_lsp/ruby_lsp_rails/document_symbol.rb
  lib/ruby_lsp/ruby_lsp_rails/support/active_support_test_case_helper.rb
  misc/document_symbol.gif
  sorbet/rbi/gems/ruby-lsp@0.14.1.rbi
  test/ruby_lsp_rails/document_symbol_test.rb
Labels: enhancement

#270 Fix runner client race condition
  Gemfile.lock
  lib/ruby_lsp/ruby_lsp_rails/addon.rb
  ruby-lsp-rails.gemspec
  test/ruby_lsp_rails/code_lens_test.rb
  test/ruby_lsp_rails/hover_test.rb
Labels: bugfix

#271 Ensure addon is initiallized in document symbol test
  test/ruby_lsp_rails/document_symbol_test.rb
Labels: chore

#269 Ignore sorbet paths for the debugger
  sorbet/rbi/shims/debug.rbi
  test/test_helper.rb
Labels: chore

#276 Set process group ID in server to terminate after parent
  lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
  test/ruby_lsp_rails/runner_client_test.rb
Labels: bugfix
