Repository Shopify/ruby-lsp-rails, pull requests merged in 2024-03, with the labels that each got.

#280 Integrate document symbol for callbacks
  lib/ruby_lsp/ruby_lsp_rails/document_symbol.rb
  lib/ruby_lsp/ruby_lsp_rails/support/active_support_test_case_helper.rb
  test/dummy/app/models/user.rb
  test/ruby_lsp_rails/document_symbol_test.rb
Labels: enhancement

#283 Implement document symbols for validations
  lib/ruby_lsp/ruby_lsp_rails/document_symbol.rb
  test/dummy/app/models/user.rb
  test/ruby_lsp_rails/document_symbol_test.rb
Labels: enhancement

#288 Update features list
  README.md
Labels: chore

#290 Fix nilable param runtime type check in server
  lib/ruby_lsp/ruby_lsp_rails/server.rb
Labels: bugfix

#293 Implement document symbol for associations
  README.md
  lib/ruby_lsp/ruby_lsp_rails/document_symbol.rb
  test/dummy/app/models/user.rb
  test/ruby_lsp_rails/document_symbol_test.rb
Labels: enhancement

#294 Change symbol appearance for Rails macros
  lib/ruby_lsp/ruby_lsp_rails/document_symbol.rb
  test/ruby_lsp_rails/document_symbol_test.rb
Labels: enhancement

#297 Add definitions for Rails callbacks
  README.md
  lib/ruby-lsp-rails.rb
  lib/ruby_lsp/ruby_lsp_rails/addon.rb
  lib/ruby_lsp/ruby_lsp_rails/definition.rb
  lib/ruby_lsp/ruby_lsp_rails/document_symbol.rb
  lib/ruby_lsp/ruby_lsp_rails/support/callbacks.rb
  misc/definition.gif
  test/dummy/app/models/user.rb
  test/ruby_lsp_rails/definition_test.rb
Labels: enhancement

#306 Centralize Ruby Version to `.ruby-version`
  .rubocop.yml
  .ruby-version
  dev.yml
  ruby-lsp-rails.gemspec
Labels: chore

#307 Remove Ruby version restriction for docs publishing
  .github/workflows/publish_docs.yml
Labels: chore
