Repository Shopify/ruby-lsp-rails, pull requests merged in 2024-05, with the labels that each got.

#339 Remove Sorbet from `server.rb`
  .gitignore
  .rubocop.yml
  lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
  lib/ruby_lsp/ruby_lsp_rails/server.rb
Labels: chore

#356 Fix thread handling
  lib/ruby_lsp/ruby_lsp_rails/addon.rb
  test/ruby_lsp_rails/definition_test.rb
Labels: chore

#352 Fix CI setup for Windows
  .github/workflows/ci.yml
  Gemfile
  Gemfile.lock
  gemfiles/Gemfile-rails-main
  lib/ruby_lsp/ruby_lsp_rails/hover.rb
  lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
  test/ruby_lsp_rails/code_lens_test.rb
  test/ruby_lsp_rails/hover_test.rb
  test/ruby_lsp_rails/runner_client_test.rb
Labels: chore

#362 Re-order CI steps
  .github/workflows/ci.yml
Labels: chore

#367 Add a `has_many through` association to the dummy app
  test/dummy/app/models/membership.rb
  test/dummy/app/models/organization.rb
  test/dummy/app/models/user.rb
  test/dummy/db/migrate/20240503152928_create_organizations.rb
  test/dummy/db/migrate/20240503153021_create_memberships.rb
  test/dummy/db/schema.rb
Labels: chore

#368 Fix markdown formatting for docs
  lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
  lib/ruby_lsp/ruby_lsp_rails/definition.rb
Labels: chore

#374 Set up DB for tests as part of default Rake task
  .github/workflows/ci.yml
  Rakefile
Labels: chore

#380 Eager load routes if necessary
  lib/ruby_lsp/ruby_lsp_rails/server.rb
Labels: bugfix

#383 Add link to Ruby DX Slack
  README.md
Labels: chore

#386 Update Dependabot config
  .github/dependabot.yml
Labels: chore

#391 Drop Ruby 3.0 in CI
  .github/workflows/ci.yml
Labels: chore

#373 Add support for jump-to-def for associations
  lib/ruby_lsp/ruby_lsp_rails/addon.rb
  lib/ruby_lsp/ruby_lsp_rails/definition.rb
  lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
  lib/ruby_lsp/ruby_lsp_rails/server.rb
  lib/ruby_lsp/ruby_lsp_rails/support/associations.rb
  lib/ruby_lsp/ruby_lsp_rails/support/location_builder.rb
  test/dummy/app/models/country.rb
  test/dummy/app/models/label.rb
  test/dummy/app/models/profile.rb
  test/dummy/app/models/user.rb
  test/dummy/db/migrate/20240521183115_create_countries.rb
  test/dummy/db/migrate/20240521183200_add_country_to_user.rb
  test/dummy/db/schema.rb
  test/ruby_lsp_rails/definition_test.rb
  test/ruby_lsp_rails/runner_client_test.rb
  test/ruby_lsp_rails/server_test.rb
  test/ruby_lsp_rails/support/location_builder_test.rb
Labels: railsconf-hackday

#395 Update for ruby-lsp v0.17
  Gemfile.lock
  lib/ruby_lsp/ruby_lsp_rails/addon.rb
  lib/ruby_lsp/ruby_lsp_rails/definition.rb
  lib/ruby_lsp/ruby_lsp_rails/hover.rb
  ruby-lsp-rails.gemspec
  sorbet/rbi/gems/actioncable@7.1.3.3.rbi
  sorbet/rbi/gems/actionmailbox@7.1.3.3.rbi
  sorbet/rbi/gems/actionmailer@7.1.3.3.rbi
  sorbet/rbi/gems/actionpack@7.1.3.3.rbi
  sorbet/rbi/gems/actiontext@7.1.3.3.rbi
  sorbet/rbi/gems/actionview@7.1.3.3.rbi
  sorbet/rbi/gems/activejob@7.1.3.3.rbi
  sorbet/rbi/gems/activemodel@7.1.3.3.rbi
  sorbet/rbi/gems/activerecord@7.1.3.3.rbi
  sorbet/rbi/gems/activestorage@7.1.3.3.rbi
  sorbet/rbi/gems/activesupport@7.1.3.3.rbi
  sorbet/rbi/gems/bigdecimal@3.1.8.rbi
  sorbet/rbi/gems/drb@2.2.1.rbi
  sorbet/rbi/gems/i18n@1.14.5.rbi
  sorbet/rbi/gems/marcel@1.0.4.rbi
  sorbet/rbi/gems/minitest@5.23.0.rbi
  sorbet/rbi/gems/mocha@2.3.0.rbi
  sorbet/rbi/gems/net-imap@0.4.11.rbi
  sorbet/rbi/gems/net-smtp@0.5.0.rbi
  sorbet/rbi/gems/nio4r@2.7.3.rbi
  sorbet/rbi/gems/nokogiri@1.16.5.rbi
  sorbet/rbi/gems/parser@3.3.1.0.rbi
  sorbet/rbi/gems/prism@0.29.0.rbi
  sorbet/rbi/gems/rack@3.0.11.rbi
  sorbet/rbi/gems/rails@7.1.3.3.rbi
  sorbet/rbi/gems/railties@7.1.3.3.rbi
  sorbet/rbi/gems/rake@13.2.1.rbi
  sorbet/rbi/gems/rbi@0.1.13.rbi
  sorbet/rbi/gems/reline@0.5.7.rbi
  sorbet/rbi/gems/rexml@3.2.8.rbi
  sorbet/rbi/gems/rubocop-ast@1.31.3.rbi
  sorbet/rbi/gems/rubocop-sorbet@0.8.3.rbi
  sorbet/rbi/gems/rubocop@1.63.4.rbi
  sorbet/rbi/gems/ruby-lsp@0.17.0.rbi
  sorbet/rbi/gems/strscan@3.1.0.rbi
  sorbet/rbi/gems/webmock@3.23.1.rbi
  sorbet/rbi/gems/zeitwerk@2.6.14.rbi
Labels: chore

#396 Remove explicit dependence on sorbet-runtime
  Gemfile.lock
  ruby-lsp-rails.gemspec
Labels: chore
