Repository Shopify/ruby-lsp-rails, pull requests merged in 2024-10, with the labels that each got.

#464 Skip directories for view paths
  lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
  test/dummy/app/views/users/index/.keep
  test/ruby_lsp_rails/code_lens_test.rb
Labels: bugfix

#471 Upgrade rexml, puma and webrick
  Gemfile.lock
  sorbet/rbi/gems/puma@6.4.3.rbi
  sorbet/rbi/gems/rbs@3.6.0.rbi
  sorbet/rbi/gems/rexml@3.3.8.rbi
  sorbet/rbi/gems/strscan@3.1.0.rbi
  sorbet/rbi/gems/webrick@1.8.2.rbi
Labels: chore

#474 Add API for delegate notifications and requests
  lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
  test/ruby_lsp_rails/runner_client_test.rb
Labels: enhancement

#478 Allow server to print debug messages
  lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
  lib/ruby_lsp/ruby_lsp_rails/server.rb
  test/ruby_lsp_rails/runner_client_test.rb
  test/ruby_lsp_rails/server_test.rb
Labels: enhancement

#479 Update for Rails 8
  Gemfile
  Gemfile.lock
  test/dummy/app/controllers/application_controller.rb
  test/dummy/app/jobs/application_job.rb
  test/dummy/app/mailers/application_mailer.rb
  test/dummy/app/views/layouts/application.html.erb
  test/dummy/app/views/layouts/mailer.html.erb
  test/dummy/bin/rails
  test/dummy/bin/rake
  test/dummy/bin/setup
  test/dummy/config/application.rb
  test/dummy/config/boot.rb
  test/dummy/config/database.yml
  test/dummy/config/environments/development.rb
  test/dummy/config/environments/production.rb
  test/dummy/config/environments/test.rb
  test/dummy/config/initializers/content_security_policy.rb
  test/dummy/config/initializers/filter_parameter_logging.rb
  test/dummy/config/initializers/permissions_policy.rb
  test/dummy/config/locales/en.yml
  test/dummy/config/puma.rb
  test/dummy/config/routes.rb
  test/dummy/db/schema.rb
  test/dummy/lib/assets/.keep
  test/dummy/public/404.html
  test/dummy/public/422.html
  test/dummy/public/500.html
  test/dummy/public/apple-touch-icon-precomposed.png
  test/dummy/public/apple-touch-icon.png
  test/dummy/public/favicon.ico
  test/ruby_lsp_rails/code_lens_test.rb
  test/ruby_lsp_rails/definition_test.rb
  test/ruby_lsp_rails/server_test.rb
Labels: chore

#498 Return `nil` on empty response
  lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
  test/ruby_lsp_rails/launch_test.rb
  test/ruby_lsp_rails/runner_client_test.rb
  test/test_helper.rb
Labels: bugfix
