Repository Shopify/ruby-lsp-rails, pull requests merged in 2024-07, with the labels that each got.

#241 Add code lens for mapping actions to routes
  README.md
  lib/ruby_lsp/ruby_lsp_rails/addon.rb
  lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
  lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
  lib/ruby_lsp/ruby_lsp_rails/server.rb
  test/dummy/app/controllers/users_controller.rb
  test/ruby_lsp_rails/code_lens_test.rb
  test/ruby_lsp_rails/server_test.rb
Labels: enhancement

#406 Prevent broken pipes leading to client errors
  lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
Labels: bugfix

#407 Fix route code lens when there are no classes in the stack
  lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
  test/ruby_lsp_rails/code_lens_test.rb
Labels: bugfix

#411 Check test framework only before pushing test code lens
  lib/ruby_lsp/ruby_lsp_rails/addon.rb
  lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
  test/ruby_lsp_rails/code_lens_test.rb
Labels: bugfix

#412 Add jump to view code lenses
  Gemfile.lock
  lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
  lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
  lib/ruby_lsp/ruby_lsp_rails/server.rb
  test/dummy/app/views/users/index.html.erb
  test/dummy/app/views/users/index.json.jbuilder
  test/ruby_lsp_rails/code_lens_test.rb
Labels: enhancement

#376 Update docs for improved Definition behaviour
  lib/ruby_lsp/ruby_lsp_rails/definition.rb
Labels: documentation

#416 Enable Dependabot for GitHub Actions
  .github/dependabot.yml
Labels: chore

#415 Bump Ruby LSP dependency to v0.17.9
  Gemfile.lock
  test/ruby_lsp_rails/hover_test.rb
Labels: chore

#421 No need to delete `Gemfile.lock` in CI for Windows
  .github/workflows/ci.yml
  Gemfile.lock
Labels: chore

#414 Rescue `IOError` during shutdown
  lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
Labels: bugfix

#426 Fix `NullClient#send_notification`
  lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
  test/ruby_lsp_rails/runner_client_test.rb
Labels: bugfix
