Repository Shopify/ruby-lsp-rails, pull requests merged in 2025-04, with the labels that each got.

#596 Add Rails test command resolution
  lib/ruby_lsp/ruby_lsp_rails/addon.rb
  lib/ruby_lsp/ruby_lsp_rails/rails_test_style.rb
  test/ruby_lsp_rails/rails_test_style_test.rb
Labels: enhancement

#599 Bump build timeout to 25 minutes
  .github/workflows/ci.yml
  Gemfile.lock
  Rakefile
  sorbet/rbi/shims/server_test.rbi
  test/ruby_lsp_rails/server_test.rb
Labels: chore

#597 Strip extra backslashes from discovered test names
  lib/ruby_lsp/ruby_lsp_rails/rails_test_style.rb
  test/fixtures/test_with_escaped_quotes.rb
  test/ruby_lsp_rails/rails_test_style_test.rb
Labels: bugfix

#600 Migrate to RBS in comments syntax
  lib/ruby_lsp/ruby_lsp_rails/addon.rb
  lib/ruby_lsp/ruby_lsp_rails/code_lens.rb
  lib/ruby_lsp/ruby_lsp_rails/completion.rb
  lib/ruby_lsp/ruby_lsp_rails/definition.rb
  lib/ruby_lsp/ruby_lsp_rails/document_symbol.rb
  lib/ruby_lsp/ruby_lsp_rails/hover.rb
  lib/ruby_lsp/ruby_lsp_rails/rails_test_style.rb
  lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
  lib/ruby_lsp/ruby_lsp_rails/server.rb
  lib/ruby_lsp/ruby_lsp_rails/support/active_support_test_case_helper.rb
  lib/ruby_lsp/ruby_lsp_rails/support/associations.rb
  lib/ruby_lsp/ruby_lsp_rails/support/callbacks.rb
  sorbet/config
  test/ruby_lsp_rails/addon_test.rb
  test/ruby_lsp_rails/runner_client_test.rb
  test/test_helper.rb
Labels: refactoring
