Repository Shopify/ruby-lsp-rails, pull requests merged in 2025-01, with the labels that each got.

#555 Reduce file watching overhead from Rails
  lib/ruby_lsp/ruby_lsp_rails/server.rb
Labels: enhancement

#557 Watch for YAML file changes for fixtures
  lib/ruby_lsp/ruby_lsp_rails/addon.rb
Labels: chore

#559 Allow server to send asynchronous notifications to client
  lib/ruby_lsp/ruby_lsp_rails/runner_client.rb
  lib/ruby_lsp/ruby_lsp_rails/server.rb
  test/ruby_lsp_rails/runner_client_test.rb
  test/ruby_lsp_rails/server_test.rb
Labels: breaking-change

#563 Show progress when reloading the Rails application
  lib/ruby_lsp/ruby_lsp_rails/server.rb
Labels: enhancement

#564 Wrap stderr in a structure log delegator
  lib/ruby_lsp/ruby_lsp_rails/server.rb
  test/ruby_lsp_rails/server_test.rb
Labels: enhancement
